### ISSUE TITLE
the `install pnpm` job breaks the whole github actions 

### ISSUE THREAD

**Issue by bnjox** [CommunityPro/ecommerce-api#64]
```yml
   - name: install pnpm
     run: npm install - pnpm
```
since we are forcing `pnpm` for the project, github actions can't run the above job to get pnpm working.

**Comment by pablo-clueless** [comment]
The issue was the steps were not in the right order and a few steps were missing. Here is the updated workflow

```
name: build-check

on:
 pull_request:
  branches:
   - dev
   - main

jobs:
 build:
  runs-on: ubuntu-latest

  steps:
   - name: check-out
     uses: actions/checkout@v4

   - name: install pnpm
     uses: pnpm/action-setup@v2
     with:
      version: 9
      run_install: false

   - name: set-up-node
     uses: actions/setup-node@v3
     with:
      node-version: 20
      cache: pnpm

   - name: install-deps
     run: pnpm install

   - name: build
     run: npm run build
```
the actions runs successfully now
